#183 fix leanpub aside syntax
isaqb-org/glossary pull request #185
Opened 2022-12-18 20:11 UTC by gernotstarke

2022-12-18 20:22 UTC, alxlo approved these changes

2022-12-18 23:05 UTC, programming-wolf requested changes
Some changes required

2022-12-18 23:05 UTC, programming-wolf commented on docs/1-terms/I/term-iso-25010.adoc
> +It is a standards to describe _software product quality_.
*standard (singular)

2022-12-18 23:05 UTC, programming-wolf commented on docs/1-terms/I/term-iso-25010.adoc
> +N
N weg

2022-12-18 23:05 UTC, programming-wolf commented on docs/1-terms/I/term-iso-25010.adoc
> +image::1_architecture/ISO-25010-EN.png
Deutsches Bild?

2022-12-18 23:05 UTC, programming-wolf commented on docs/1-terms/S/term-software-architecture.adoc
> +[NOTE]
Bitte wieder entfernen. Ich habe hier bewusst diese Form genommen, da sie zur Hervorhebung des Zitats verwendet wird. NOTE passt da nicht. Im deutschen Bereich bitte auch entfernen.

2022-12-18 23:05 UTC, programming-wolf commented on docs/1-terms/S/term-software-architecture.adoc
> +[NOTE]
Hier weg

2022-12-20 06:59 UTC, gernotstarke commented on docs/1-terms/S/term-software-architecture.adoc
> +[NOTE]
im released-glossary steckt noch das alte leanpub markdown A> drin...

2022-12-20 08:44 UTC, programming-wolf approved these changes

2022-12-20 08:48 UTC, merged